### ISSUE TITLE
Use proper ROS-I Joint Trajectory Messages

### ISSUE THREAD

**Issue by GeorgHeppner** [fzi-forschungszentrum-informatik/schunk_svh_driver#2]
Currently the input is done with a sensor message wich could be improved to use the ROS-I standard of JointTrajectoryMessages.

The previous interface should remain stable

**Comment by gavanderhoorn** [comment]
Just a small remark: the JointTrajectory msg type is not ROS-I specific, its part of the generic [trajectory_msgs](http://wiki.ros.org/trajectory_msgs) pkg.

**Comment by beckerpascal** [comment]
Closed due inactivity.
