### ISSUE TITLE
Remove the sleep in communication

### ISSUE THREAD

**Issue by GeorgHeppner** [fzi-forschungszentrum-informatik/schunk_svh_driver#5]
In the current version an arbitrary sleep time is used in communication:
https://github.com/fzi-forschungszentrum-informatik/schunk_svh_driver/blob/master/src/driver_svh/src/driver_svh/SVHSerialInterface.cpp#L158

This is not good as it slows down communication speed and might be hardware dependent. It has been identified that the problem is actually the message length which needs to be padded accordingly.

While this is not very beautiful and should be fixed it has not yet lead to issues with the communication.

**Comment by beckerpascal** [comment]
Closed due inactivity.
