### ISSUE TITLE
DH parameters for schunk svh hand?

### ISSUE THREAD

**Issue by v-wewei** [fzi-forschungszentrum-informatik/schunk_svh_driver#8]

**Comment by GeorgHeppner** [comment]
There is a detailed Kinematic description here: http://wiki.ros.org/schunk_svh_driver#Additional_information also you can see the link transformations in the URDF https://github.com/fzi-forschungszentrum-informatik/schunk_svh_driver/blob/master/description/urdf/svh.urdf.xacro as the rotational axis are always Z this is basically conforming to DH.
